sudo: required
dist: trusty
language: c
env:
  - LLVM_TARGET_VERSION=3.4 LLVM_STATIC=no LIBS="-lncurses -ldl -lpthread"
  - LLVM_TARGET_VERSION=3.5 LLVM_STATIC=no
  - LLVM_TARGET_VERSION=3.6 LLVM_STATIC=no
  - LLVM_TARGET_VERSION=3.4 LLVM_STATIC=yes LIBS="-lncurses -ldl -lpthread"
  - LLVM_TARGET_VERSION=3.5 LLVM_STATIC=yes
  - LLVM_TARGET_VERSION=3.6 LLVM_STATIC=yes
  - LLVM_TARGET_VERSION=3.7 LLVM_STATIC=yes
  - LLVM_TARGET_VERSION=3.8 LLVM_STATIC=yes
  - LLVM_TARGET_VERSION=3.9 LLVM_STATIC=yes
  - LLVM_TARGET_VERSION=4.0 LLVM_STATIC=yes
before_script:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - echo -e "deb http://ppa.launchpad.net/jonathonf/llvm/ubuntu trusty main\ndeb http://apt.llvm.org/trusty/ llvm-toolchain-trusty main\ndeb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.8 main\ndeb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.9 main" | sudo tee /etc/apt/sources.list.d/llvm.list
  - sudo apt-get update
  - sudo apt-get install -qq -y --force-yes devscripts equivs gcc-4.9 g++-4.9
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 60 --slave /usr/bin/g++ g++ /usr/bin/g++-4.9
  - sed -i -e 's/, *llvm-[0-9.-]*dev[^,]*,/,/g' debian/control
  - sudo mk-build-deps -i -t "apt-get -qq -y --force-yes --no-install-recommends"
  - sudo apt-get install -qq -y --force-yes llvm-${LLVM_TARGET_VERSION}-dev
script: "./.travis.sh"
notifications:
  on_success: never
  on_failure: change
deploy:
  provider: s3
  access_key_id: AKIAJY7JELRUQJ6ESEWA
  secret_access_key:
    secure: TPcW3NIOHVrMZDmzXs22ZucjlM2+TASAG7LEitAtoZSvLyce08JgC0R00mK+PCRBfXiRspxvh0rmaJGAecZXSaazth5IV9Np2xGPeQ6G/6s3KzfdoFNlAs/MlZVNVNbq3l3R5ZF3DUwy6DThDvSjMLDwSEBWSlOLgz7tA3moxK0=
  bucket: artefacts.masella.name
  skip_cleanup: true
  local_dir: www
  acl: public_read
