sudo: required
dist: trusty
language: c
before_script:
  - sudo apt-get install -qq -y --force-yes devscripts equivs
  - sudo mk-build-deps -i -t "apt-get -qq -y --force-yes --no-install-recommends"
script: "./autogen.sh && ./configure --enable-llvm-static=no && make && make check"
notifications:
  on_success: never
  on_failure: change
