.\" Authors: Paul Boutros and Lab Members
.TH barf_queries 7 "Dec 2014" "1.0" "MISCELLANEOUS"
BARF filters SAM or BAM files using a simple query language that is more expressive than the
.B view
options available in
.BR samtools (1).

The language consists of logical connectives, specifically and, or, not, and a ternary if, and predicates that match properties of the read. Expressions may be grouped using parentheses.

.SH LOGICAL CONNECTIVES
The logical connectives are presented in order from lowest precedence to highest precedence.

.SS TERNARY IF
cond \fBthen\fR then_expression \fBelse\fR else_expression

If \fIcond\fR is satisfied, this expression will only be satisfied if \fIthen_expression\fR is satisfied. If \fIcond\fR is not satisfied, then this expression will only be satisfied if \fIelse_expression\fR is satisfied.

.SS DISJUNCTION (OR)
expr \fB|\fR expr

Is satisfied if at least one operand is satisfied.

.SS EXCLUSIVE DISJUNCTION (XOR)
expr \fB^\fR expr

Is satisfied if exactly one operand is satisfied, but not both.

.SS CONJUNCTION (AND)
expr \fB&\fR expr

Is satisfied only if both operands are satisfied.

.SS NEGATION (NOT)
\fB!\fR expr

Is satisfied if \fIexpr\fR is not satisfied.

.SH PREDICATES
The predicates are grouped based on function.

.SS BAM FLAGS
These predicates match the sequences in the BAM file. For more details, see
.BR sam (5).

.B paired?

The read is paired in sequencing.

.B proper_pair?

The read is mapped in a proper pair; that is, the aligner thought the insert size implied by the paired-end reads seemed correct.

.B unmapped?

The query sequence itself is unmapped.

.B mate_unmapped?

The mate is unmapped.

.B mapped_to_reverse?

The read is mapped to the reverse strand.

.B mate_mapped_to_reverse?

The read's mate is mapped to the reverse strand.

.B read1?

The read is the first read in a pair.

.B read2?

The read is the second read in a pair.

.B secondary?

The alignment is not primary.

.B failed_qc?

The read fails platform/vendor quality checks.

.B duplicate?

The read is either a PCR or an optical duplicate. That is, another read with the same sequence occurs at exactly the same position in the reference genome.

.B supplementary?

The alignment is supplementary.

.SS MAPPING INFORMATION
\fBchr(\fRglob\fB)\fR

Matches the chromosome name to which the read is mapped. Chromosome names should not start with \fBchr\fR, as that will be automatically checked. Moreover, some human chromosome have differing names, so both are checked. The known rules are:

X == 23
.br
Y == 24
.br
MT == M == 25


Also, case is ignored. Additionally, the chromosome is matched using wildcards from 
.BR glob (7).

\fBmapping_quality(\fRprobability\fB)\fR

Matches the read if the probability of error is less than \fIprobability\fR. The mapping quality is approximated in the SAM format, so this will be imperfect. For clarity, setting the probability to 0 will be so stringent as to reject all reads, while setting it to 1 will be so liberal as to accept all reads.

\fBmate_chr(\fRglob\fB)\fR

This works identically to \fBchr\fR, but on the chromosome of the mate pair, if one exists. If the mate is unmapped, this returns false.

\fBsplit_pair?\fR

Checks if both the reads in a mate pair are mapped, but to different chromosomes.

.SS OTHER READ INFORMATION
\fBread_group(\fRglob\fB)\fR

Matches the read group, if specified in the input. The read group may be specified using
.BR glob (7)
to match multiple read groups. 

.SS POSITION
\fBafter(\fRposition\fB)\fR

Matches all sequences that cover the specified position or any higher position (more \fIq\fR-ward on the chromosome).

\fBbefore(\fRposition\fB)\fR

Matches all sequences that cover the specified position or any lower position (more \fIp\fR-ward on the chromosome).

\fBposition(\fRstart\fB,\fR end\fB)\fR

Matches all sequences that cover the range of position from \fIstart\fR to \fIend\fR.

.SS SEQUENCE
\fBnt(\fRposition\fB,\fR n\fB)\fR

Matches a read has nucleotide \fIn\fR at the provided position, relative to the chromosome. The nucleotide can be any IUPAC-style base (ACGTU, KMYR, BDHV, and N). The match is degenerate; that is, if the nucleotide specified is N, any base will match. It will reject unmapped reads and reads which do not contain the required position.

\fBnt_exact(\fRposition\fB,\fR n\fB)\fR

Matches a read has nucleotide \fIn\fR at the provided position, relative to the chromosome. The nucleotide can be any IUPAC-style base (ACGTU, KMYR, BDHV, and N). The match is exact; that is, if the nucleotide specified is N, the base in the read must be N too. It will reject unmapped reads and reads which do not contain the required position.

.SS MISCELLANEOUS

.B true

Always satisfied.

.B false

Never satisfied.

\fBrandom(\fRprobability\fB)\fR

This chooses a uniform pseudo-random variable and is satisfied with frequency \fIprobability\fR. This can be used to provide a random sub-sample of reads. The probability must be between 0 and 1 and can be specified using scientific notation. The random number chosen is selected using
.BR drand48 (3)
if one is inclined to care about such things.

.SH EXAMPLES

Match sequences on chromosome 7 which are from the read group labelled \fBRUN3\fR:

.B "chr(7) & read_group(RUN3)"

Sub-sample mitochondrial reads and all the reads that have matched to chromosomes starting with \fBug\fR.

.B "chr(M) & random(0.2) | chr(ug*)"

.SH SEE ALSO
.BR barf (1),
.BR barf-compile (1),
.BR samtools (1).
