.\" Authors: Paul Boutros and Lab Members
.TH bamql-pairs 1 "Jan 2017" "1.2" "USER COMMANDS"
.SH NAME 
bamql-pairs \- Filter SAM/BAM read pairs easily
.SH SYNOPSIS
.B bamql
[
.B \-b
] [
.B \-I
]
.B -f
.I input.bam
.B \-o 
.I output.bam
{
.B -q
.I query.bamql
|
.I query
}
.SH DESCRIPTION
BAMQL filters SAM or BAM files using a simple query language that is more expressive than the
.B view
options available in
.BR samtools (1).
The query language is described in
.BR bamql_queries (7).

.SH OPTIONS
.TP
\-b
Opens the input as BAM format, rather than SAM format.
.TP
\-f input.bam
The input BAM file.
.TP
\-I
Ignore the index, if present. BAM files can be indexed, allowing more efficient searching of the file. If an index is found, it will be automatically used. This switch ignore the index even if it is present; it makes no difference if it is not.
.TP
\-o output.bam
Any read pairs which are accepted by the query, that is, for which the query is true, will be placed in this file. Unlike
.BR bamql (1)
if either member of a read pair is accepted, both are accepted. This requires reading the file twice, so it will be slower.
.TP
\-q query.bamql
Read the query from a file. To run this query from the command line, as a script, set the first line of the file to be \fB#!/usr/bin/env bamql-script\fR. See
.BR bamql-script (1).

.SH SEE ALSO
.BR bamql (1),
.BR bamql-chain (1),
.BR bamql-compile (1),
.BR bamql-script (1),
.BR bamql_queries (7),
.BR samtools (1).
