.\" Authors: Paul Boutros and Lab Members
.TH bamql 1 "Dec 2014" "1.0" "USER COMMANDS"
.SH NAME 
bamql \- Filter SAM/BAM files easily
.SH SYNOPSIS
.B bamql
[
.B \-b
] [
.B \-I
] [
.B \-o 
.I accepted_output.bam
] [
.B \-O
.I rejected_output.bam
]
.B -f
.I input.bam
{
.B -q
.I query.bamql
|
.I query
}
.SH DESCRIPTION
BAMQL filters SAM or BAM files using a simple query language that is more expressive than the
.B view
options available in
.BR samtools (1).
The query language is described in
.BR bamql_queries (7).

.SH OPTIONS
.TP
\-b
Opens the input as BAM format, rather than SAM format.
.TP
\-f input.bam
The input BAM file.
.TP
\-I
Ignore the index, if present. BAM files can be indexed, allowing more efficient searching of the file. If an index is found, it will be automatically used. This switch ignore the index even if it is present; it makes no difference if it is not.
.TP
\-o accepted_output.bam
Any reads which are accepted by the query, that is, for which the query is true, will be placed in this file. If omitted, the number of queries will be tallied, but discarded
.TP
\-O rejected_output.bam
Any reads which are rejected by the query, that is, for which the query is false, will be placed in this file. If omitted, the number of queries will be tallied, but discarded
.TP
\-q query.bamql
Read the query from a file. This allows the query to be put in a file with a first line of \fB#!/usr/bin/bamql -q\fR such that it can be invoked from the shell.

.SH EXAMPLE
This extracts all the reads on chromosome 7:

.B bamql -o chromo7.bam -b -f genome.bam 'chr(7)'

.SH SEE ALSO
.BR bamql-chain (1),
.BR bamql-compile (1),
.BR bamql_queries (7),
.BR samtools (1).
