.\" Authors: Paul Boutros and Lab Members
.TH bamql 1 "Feb 2015" "1.0" "USER COMMANDS"
.SH NAME 
bamql \- Filter SAM/BAM files easily through a chain of filters
.SH SYNOPSIS
.B bamql-chain
[
.B \-b
] [
.B \-c
.I method
] [
.B \-I
] [
.B \-f 
.I input.bam
]
.I query1
.I output1.bam
.I query2
.I output2.bam
.SH DESCRIPTION
BAMQL filters SAM or BAM files using a simple query language that is more expressive than the
.B view
options available in
.BR samtools (1).
The query language is described in
.BR bamql_queries (7).

Unlike 
.BR bamql (1),
this sends each read down a collection of queries, either in parallel, the default, or in another configuration using the \fB-c\fR option.

If the output of a particular query is uninteresting, it can be discarded by specifying \fB-\fR for the output file name.

.SH OPTIONS
.TP
\-b
Opens the input as BAM format, rather than SAM format.
.TP
\-c method
Arrange the queries. See \fBCHAINING\fR for details.
.TP
\-f input.bam
The input BAM file.
.TP
\-I
Ignore the index, if present. BAM files can be indexed, allowing more efficient searching of the file. If an index is found, it will be automatically used. This switch ignore the index even if it is present; it makes no difference if it is not.

.SH CHAINING
Chains of queries can be put into several configurations.

.TP
.B parallel
This is the default. Each read is independently given to all queries.
.TP
.B series
A read is given to the first query. If it passes the query, it is saved and only then, passed to the next query.
.TP
.B shuttle
A read is given to the first query. If it passes the query, it is saved and processing stops. If it fails, it is passed to the next query.

.SH EXAMPLE
This extracts all the reads on chromosome 7 and all the paired reads:

.B bamql-chain -b -f genome.bam 'chr(7)' chromo7.bam 'paired?' paired.bam

This extracts all the reads on chromosome 7 and all the paired reads on chromosome 7:

.B bamql-chain -b -f genome.bam -c series 'chr(7)' chromo7.bam 'paired?' chromo7_paired.bam

This extracts all the reads on chromosome 7 and all the paired reads that are on other chromosomes:

.B bamql-chain -b -f genome.bam -c shuttle 'chr(7)' chromo7.bam 'paired?' paired_except_chr7.bam

.SH SEE ALSO
.BR bamql (1),
.BR bamql-compile (1),
.BR bamql_queries (7),
.BR samtools (1).
